apiVersion: v1
kind: Service
metadata:
  name: shinko-service
  namespace: shinko
spec:
  selector:
    app: shinko-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
