# This rule is not used by the project shinko-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over app.shinko.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: shinko-operator
    app.kubernetes.io/managed-by: kustomize
  name: shinkoapp-admin-role
rules:
- apiGroups:
  - app.shinko.io
  resources:
  - shinkoapps
  verbs:
  - '*'
- apiGroups:
  - app.shinko.io
  resources:
  - shinkoapps/status
  verbs:
  - get
