# This rule is not used by the project shinko-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to app.shinko.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: shinko-operator
    app.kubernetes.io/managed-by: kustomize
  name: shinkoapp-viewer-role
rules:
- apiGroups:
  - app.shinko.io
  resources:
  - shinkoapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.shinko.io
  resources:
  - shinkoapps/status
  verbs:
  - get
