apiVersion: app.shinko.io/v1alpha1
kind: ShinkoDB
metadata:
  labels:
    app.kubernetes.io/name: shinko-operator
    app.kubernetes.io/managed-by: kustomize
  name: shinkodb-sample
spec:
  # TODO(user): Add fields here
